protocol: 'https:'
host: 'lab.ueda.tech'
sitetitle: '千葉工大自律ロボット研究室'
subtitle: '（上田研究室）'
headline:
- text: '以前のWordpress製のサイトをラボ主がぶっ壊してしまいましたのでbashcms2に引っ越しました。まだリンク等、おかしいところがあります。'
twitter:
- account: 'uedalaboratory'
facebook: '@'
hatena: '@'
pocket: '@'
line: '@'
links:
- text: 'latest'
  href: '/?post'
- text: 'publications'
  href: '/?page=publication'
sociallinks:
- icon: 'fa-twitter-square'
  href: 'https://twitter.com/uedalaboratory'
