protocol: 'https:'
host: 'lab.ueda.tech'
sitetitle: '千葉工大自律ロボット研究室'
subtitle: '上田隆一研究室'
headline:
- text: '以前のWordpress製のサイトをラボ主がぶっ壊してしまいましたのでbashcms2に引っ越しました。まだリンク等、おかしいところがあります。'
twitter:
- account: 'uedalaboratory'
facebook: '@'
hatena: '@'
pocket: '@'
line: '@'
links:
- text: '最新記事'
  href: '/?post'
- text: 'メンバー'
  href: '/?page=member'
- text: '文献'
  href: '/?page=publication'
- text: '講義'
  href: '/?page=lecture'
- text: 'プロジェクト'
  href: '/?page=project'
- text: '共同研究の案内'
  href: '/?page=collaboration_info'
- text: '外部リンク'
  href: '#'
  sublinks:
  - text: '千葉工業大学'
    href: 'https://www.it-chiba.ac.jp/'
sociallinks:
- icon: 'fa-twitter-square'
  href: 'https://twitter.com/uedalaboratory'
